In [4]:
!pip install pandas

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
soc=pd.read_csv("Social_Network_Ads.csv")
soc.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
X=soc.iloc[:,[2,3]].values
y=soc.iloc[:,4].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [40]:
# spliiting the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=4)

In [41]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [42]:
X_train

array([[-0.94662201, -0.78624689],
       [-0.36979032, -0.8156904 ],
       [-0.08137447, -0.2562637 ],
       [-0.2736517 ,  0.59759811],
       [ 1.45684338,  2.12866066],
       [-1.13889924,  0.303163  ],
       [ 0.11090276,  0.0087279 ],
       [ 0.01476414, -0.28570721],
       [ 0.39931861,  0.5681546 ],
       [ 0.88001168, -1.08068199],
       [ 0.30317999, -0.5506988 ],
       [-1.23503786,  0.24427598],
       [ 1.93753645, -0.69791635],
       [-0.56206755,  1.89311257],
       [-0.2736517 , -0.60958582],
       [-0.08137447,  2.21699119],
       [-0.65820616, -0.37403774],
       [-0.56206755,  0.8625897 ],
       [-0.08137447, -0.5506988 ],
       [-0.94662201, -0.99235146],
       [ 2.12981369, -1.08068199],
       [ 0.9761503 ,  2.06977363],
       [ 0.30317999,  0.27371949],
       [ 0.39931861, -0.49181178],
       [ 1.36070476, -1.46344763],
       [ 0.39931861,  0.12650194],
       [-0.75434478,  1.06869428],
       [ 0.88001168, -1.34567359],
       [-1.42731509,

In [43]:
X_test

array([[-0.46592893, -0.31515072],
       [-1.04276063,  0.39149353],
       [-1.23503786,  0.47982407],
       [ 0.01476414, -0.60958582],
       [-1.04276063,  0.50926758],
       [ 1.84139784, -1.31623008],
       [ 0.78387307,  0.50926758],
       [ 1.36070476,  1.9814431 ],
       [ 1.07228892,  0.53871109],
       [ 0.01476414, -0.58014231],
       [ 0.01476414, -0.34459423],
       [-1.04276063, -0.49181178],
       [-1.23503786,  0.27371949],
       [ 0.30317999, -0.31515072],
       [ 0.30317999, -0.58014231],
       [-0.36979032, -0.8156904 ],
       [-1.13889924, -0.5506988 ],
       [-1.13889924, -1.64010869],
       [-1.33117647, -0.46236827],
       [-1.33117647, -1.52233465],
       [-0.17751309, -0.49181178],
       [-0.94662201, -0.34459423],
       [-1.90800817,  0.33260651],
       [ 1.93753645,  0.71537215],
       [ 0.30317999,  0.03817141],
       [ 1.84139784,  1.51034693],
       [-1.04276063,  0.74481566],
       [ 0.20704138,  0.03817141],
       [-1.71573093,

In [50]:
from sklearn.svm import SVC
sup=SVC()
sup.fit(X_train,y_train)
pred=sup.predict(X_test)

In [51]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,pred)
cm

array([[74,  7],
       [ 2, 37]], dtype=int64)

In [52]:
from sklearn import metrics 
print(metrics.accuracy_score(y_test,pred)) 

0.925


In [47]:
from sklearn.svm import SVC
sup1=SVC(kernel='rbf',gamma=80)
sup1.fit(X_train,y_train)
pred1=sup1.predict(X_test)

In [48]:
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y_test,pred)
cm1

array([[76,  5],
       [10, 29]], dtype=int64)

In [49]:
from sklearn import metrics 
print(metrics.accuracy_score(y_test,pred)) 

0.875


In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94        81
           1       0.84      0.95      0.89        39

    accuracy                           0.93       120
   macro avg       0.91      0.93      0.92       120
weighted avg       0.93      0.93      0.93       120

